const std = @import("std");
const TokenType = @import("../enums/token_type.zig").TokenType;

pub const tokenMap = std.StaticStringMap(TokenType).initComptime(.{
    .{ "fn", TokenType.fn_token },
    .{ "var", TokenType.var_token },
    .{ "const", TokenType.const_token },
    .{ "if", TokenType.if_token },
    .{ "else", TokenType.else_token },
    .{ "for", TokenType.for_token },
    .{ "while", TokenType.while_token },
    .{ "stream", TokenType.stream_token },
    .{ "in", TokenType.in_token },
    .{ "true", TokenType.true_literal_token },
    .{ "false", TokenType.false_literal_token },
    .{ "void", TokenType.void_token },
    .{ "not", TokenType.not_token },
    .{ "and", TokenType.and_token },
    .{ "or", TokenType.or_token },
    .{ "import", TokenType.import_token },
    .{ "int", TokenType.integer_type_token },
    .{ "bool", TokenType.boolean_type_token },
    .{ "string", TokenType.string_type_token },
    .{ "catch", TokenType.catch_token },
    .{ "struct", TokenType.struct_token },
    .{ "as", TokenType.as_token },
    .{ "return", TokenType.return_token },
    .{ "extern", TokenType.extern_token },
    .{ "val", TokenType.value_type_token },
    .{ "arr", TokenType.array_type_token },
    .{ "break", TokenType.break_token },
    .{ "continue", TokenType.continue_token },
});
