pub const TokenType = enum {
    init,

    eof_token,
    error_token,

    identifier_token,

    integer_type_token,
    string_type_token,
    char_type_token,
    boolean_type_token,

    integer_literal_token,
    string_literal_token,
    char_literal_token,
    multile_string_literal_token,
    true_literal_token,
    false_literal_token,
    void_token,

    not_token,
    fn_token,
    var_token,
    const_token,
    if_token,
    else_token,
    for_token,
    in_token,
    true_token,
    false_token,
    return_token,
    import_token,

    and_token,
    or_token,
    pipeline_token,
    assign_token,
    equal_token,
    bang_equal_token,
    less_token,
    less_equal_token,
    greater_token,
    greater_equal_token,
    plus_token,
    minus_token,
    star_token,
    slash_token,
    remainder_token,
    lparen_token,
    rparen_token,
    lbrace_token,
    rbrace_token,
    lbracket_token,
    rbracket_token,
    colon_token,
    comma_token,
    semicolon_token,
    dot_token,
};
