name: Flint CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Target Dependencies (Clang & libcurl)
      run: |
        sudo apt-get update
        sudo apt-get install -y clang libcurl4-openssl-dev
    
    - name: Install Zig 0.15.2 (Manual Bypass)
      run: |
        wget -q https://ziglang.org/download/0.15.2/zig-0.15.2.tar.xz
        tar -xf zig-0.15.2.tar.xz
        sudo mv zig-0.15.2 /usr/local/zig
        sudo ln -s /usr/local/zig/zig /usr/local/bin/zig
        zig version

    - name: Build Flint
      run: zig build -Doptimize=ReleaseFast

    - name: Run Test Battery
      run: ./zig-out/bin/flint test