name: Flint CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Target Dependencies (Clang & libcurl)
      run: |
        sudo apt-get update
        sudo apt-get install -y clang libcurl4-openssl-dev
    
    - name: Cache Zig
        uses: actions/cache@v4
        with:
          path: /opt/zig
          key: zig-0.15.2

    - name: Install Zig
      run: |
        if [ ! -f /opt/zig/zig ]; then
          wget -q https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz
          tar -xf zig-x86_64-linux-0.15.2.tar.xz
          sudo mv zig-x86_64-linux-0.15.2 /opt/zig
        fi
        echo "/opt/zig" >> $GITHUB_PATH

    - name: Verify Zig
      run: zig version

    - name: Build Flint
      run: zig build -Doptimize=ReleaseFast

    - name: Run Test Battery
      run: ./zig-out/bin/flint test